In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_excel(r"D:\360Downloads\风行数据中心实战\数据集\处理之后的数据\user_unit.xlsx",index_col=0)
df.head()

,id,用户名称,用电单元名称,时间,0:00:00,0:15:00,0:30:00,0:45:00,1:00:00,1:15:00,...,21:45:00,22:00:00,22:15:00,22:30:00,22:45:00,23:00:00,23:15:00,23:30:00,23:45:00,00:00:00
0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-01,0.0,0.000,0.000,0.000,0.020,0.000,...,0.098,0.118,0.098,0.098,0.118,0.098,0.118,0.078,0.274,NaN
1,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-02,0.0,0.039,0.118,0.098,0.118,0.098,...,0.039,0.098,0.118,0.098,0.098,0.098,0.118,0.078,0.235,NaN
2,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-03,0.0,0.039,0.118,0.098,0.098,0.098,...,0.118,0.118,0.059,0.118,0.098,0.098,0.118,0.098,0.274,NaN
3,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-04,0.0,0.039,0.098,0.118,0.098,0.118,...,0.000,0.000,0.000,0.020,0.000,0.000,0.000,0.000,0.020,NaN
4,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-05,0.0,0.000,0.000,0.000,0.020,0.000,...,0.098,0.098,0.118,0.098,0.098,0.098,0.098,0.098,0.255,NaN

In [123]:
df = df.rename(columns={"id":"用电单元id"})
df.head(1)

,用电单元id,用户名称,用电单元名称,时间,0:00:00,0:15:00,0:30:00,0:45:00,1:00:00,1:15:00,...,21:45:00,22:00:00,22:15:00,22:30:00,22:45:00,23:00:00,23:15:00,23:30:00,23:45:00,00:00:00
0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-01,0.0,0.0,0.0,0.0,0.02,0.0,...,0.098,0.118,0.098,0.098,0.118,0.098,0.118,0.078,0.274,NaN

In [128]:
df.insert(0,"用户id",0)
df

,用户id,用电单元id,用户名称,用电单元名称,时间,0:00:00,0:15:00,0:30:00,0:45:00,1:00:00,...,21:45:00,22:00:00,22:15:00,22:30:00,22:45:00,23:00:00,23:15:00,23:30:00,23:45:00,00:00:00
0,0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-01,0.000,0.000,0.000,0.000,0.020,...,0.098,0.118,0.098,0.098,0.118,0.098,0.118,0.078,0.274,NaN
1,0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-02,0.000,0.039,0.118,0.098,0.118,...,0.039,0.098,0.118,0.098,0.098,0.098,0.118,0.078,0.235,NaN
2,0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-03,0.000,0.039,0.118,0.098,0.098,...,0.118,0.118,0.059,0.118,0.098,0.098,0.118,0.098,0.274,NaN
3,0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-04,0.000,0.039,0.098,0.118,0.098,...,0.000,0.000,0.000,0.020,0.000,0.000,0.000,0.000,0.020,NaN
4,0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-05,0.000,0.000,0.000,0.000,0.020,...,0.098,0.098,0.118,0.098,0.098,0.098,0.098,0.098,0.255,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59253,0,31319212,高平市全兴发展有限公司,高平市全兴发展有限公司31319212,2020-12-30,0.000,0.014,0.000,0.014,0.000,...,0.014,0.000,0.014,0.000,0.014,0.000,0.014,0.000,0.000,NaN
59254,0,31319457,高平市安顺兴选煤有限公司,高平市安顺兴选煤有限公司31319457,2020-12-30,0.009,0.005,0.009,0.009,0.005,...,0.014,0.005,0.009,0.014,0.005,0.009,0.009,0.009,0.009,NaN
59255,0,31347514,高平市晋昌洗煤有限公司,高平市晋昌洗煤有限公司31347514,2020-12-30,0.114,0.123,0.114,0.133,0.114,...,0.114,0.123,0.114,0.123,0.114,0.133,0.114,0.123,0.114,NaN
59256,0,1767039849,黎城太行钢铁有限公司,黎城太行钢铁有限公司1767039849,2020-12-30,7.187,7.187,6.534,6.534,6.534,...,7.187,6.534,6.534,6.534,6.534,6.534,5.881,6.534,5.881,NaN
59257,0,9885871,黎城太行钢铁有限公司,黎城太行钢铁有限公司9885871,2020-12-30,1.307,3.267,1.960,2.614,2.614,...,1.960,2.614,2.614,1.960,2.614,1.960,1.307,2.614,1.960,NaN

In [205]:
df.iloc[1,2]

'大同煤矿集团忻州同华煤业有限公司'

In [216]:
name = df1['用户名称'].value_counts().index.tolist()
name_dict={i:j for i,j in enumerate(name)}

In [217]:
name_dict

{0: '大同煤矿集团轩岗煤电有限责任公司',
 1: '山西黎城粉末冶金有限责任公司',
 2: '长治市胖妞食品有限公司',
 3: '山西成功淮海发动机有限公司',
 4: '山西长清生物科技有限公司',
 5: '繁峙县中盛铁选厂',
 6: '中铝山西新材料有限公司',
 7: '永济市鑫源铁合金铸造有限公司',
 8: '灵石县红星煤化有限公司',
 9: '长治市安迪建材有限公司',
 10: '怀仁县金沙滩天丰建材有限公司',
 11: '山西忻州神达台基麻地沟煤业有限公司',
 12: '岢岚县凯裕石料厂',
 13: '高平市安顺兴选煤有限公司',
 14: '山西晋牌水泥集团晋川建材有限公司',
 15: '河津市荣盛洗煤锌业有限公司',
 16: '代县万丰矿粉精加工厂',
 17: '大同煤矿集团临汾宏大豁口煤业有限公司',
 18: '阳高县瑞星建材有限公司',
 19: '代县福泰选矿有限公司',
 20: '怀仁市陈家堡储售煤炭有限责任公司',
 21: '襄汾县新金山特钢有限公司',
 22: '山煤国际能源集团朔州有限公司大峪口选煤厂',
 23: '繁峙县恒煜节能环保建材有限公司',
 24: '大同市云冈区旭晨洗煤有限公司',
 25: '北京汇源集团万荣有限公司',
 26: '代县金宝来选矿厂',
 27: '长治市致诚盛业新型材料有限公司',
 28: '山西忻州神达晋保煤业有限公司',
 29: '灵石县隆鑫煤化有限公司',
 30: '山西忻州神达望田煤业有限公司',
 31: '长治市九牛寨乳业有限公司',
 32: '怀仁县鸿浩建材有限公司',
 33: '山西鑫瑞达冶金机械制造有限公司',
 34: '灵石县鑫泰煤化有限公司',
 35: '山西华融龙宫煤业有限责任公司',
 36: '运城汇源食品饮料有限公司',
 37: '山西忻州神达大桥沟煤业有限公司',
 38: '襄垣县鸿盛洗选煤有限公司',
 39: '大同煤矿集团临汾宏大雪坪煤业有限公司',
 40: '山西集华兴业煤炭有限公司',
 41: '山西巴瑞新材料有限公司',
 42: '山西格瑞利节能科技有限公司',
 43: '永济市三众电气制造有限公司',
 44: '灵石县森荣炳煤化有限公司',
 45: '大同市云冈区华宇煤业有限公司',
 46: '山西昶达能源有限公司',
 47: '潞城市九元活性石灰有限公司',
 48: '灵石县山河煤化有限责任公司',
 49: '大同煤矿集团临汾宏大锦程煤业有限公司',
 50: '大西铁路客运专线有限责任公司',
 51: '河曲县旭阳洗选煤有限责任公司',
 52: '繁峙县福顺球团厂',
 53: '阳高县晨昀碳素有限责任公司',
 54: '怀仁县鑫源铸造厂',
 55: '山西世纪建材有限公司',
 56: '孝义市河东成旺新材料有限责任公司',
 57: '山纳合成橡胶有限责任公司',
 58: '河曲县永昌机械制造有限公司',
 59: '大同煤矿集团临汾宏大胜利煤业有限公司',
 60: '山西吉港冠宇水泥有限公司',
 61: '长治市中天汽车半轴有限公司',
 62: '山西佳鑫达食品有限公司',
 63: '太原狮头中联水泥有限公司',
 64: '大同煤矿集团阳方口矿业有限责任公司',
 65: '大同煤矿通泰橡胶有限公司',
 66: '长治市九鼎汽车配件有限公司',
 67: '大同市南郊区鑫宏伟煤业有限公司',
 68: '高平市全兴发展有限公司',
 69: '介休市志尧碳素有限公司',
 70: '永济市国强食品有限公司',
 71: '山西漳电圣科建材有限公司',
 72: '山西同朔水泥有限责任公司',
 73: '灵石县伟鑫煤化有限责任公司',
 74: '潞城市兴业煤化有限公司',
 75: '繁峙县神邦恒盛矿业有限公司',
 76: '大同首安通科技有限公司',
 77: '山西中达铝业有限责任公司',
 78: '山西长治联盛西掌煤业有限公司',
 79: '潞城市亿兴建材有限公司',
 80: '灵石县神南山煤化有限公司',
 81: '长治县宏泰实业有限公司',
 82: '山西长信工业有限公司',
 83: '大同市金源高岭土有限公司',
 84: '大同市云冈区鹏泰煤业有限公司',
 85: '山西省交城县天龙化工实业有限公司',
 86: '长治市恒晋矿业有限公司',
 87: '山西鑫洋煤业有限公司',
 88: '山西中升钢铁有限公司',
 89: '山西太顺特种泵业有限公司',
 90: '高平市晋昌洗煤有限公司',
 91: '大同市南郊区祺佳精煤有限责任公司',
 92: '黎城太行钢铁有限公司',
 93: '山西省繁峙县国鑫铁选厂',
 94: '中国石油天然气股份有限公司山西煤层气勘探开发分公司',
 95: '长治县凯承工贸有限责任公司',
 96: '山西潞宝集团晋钢兆丰煤化工有限公司',
 97: '山西开元活性炭有限公司',
 98: '平顺县广泰和矿业有限公司',
 99: '晋西装备制造有限责任公司',
 100: '代县龙华矿业有限责任公司',
 101: '河津市民政福利煤化有限公司',
 102: '大同市新荣区联荣精煤有限责任公司',
 103: '山西同冠新材料有限公司',
 104: '长治市榕泽矿业有限公司',
 105: '山西忻州神达梁家碛煤业有限公司',
 106: '山西宏达钢铁集团有限公司',
 107: '山西卦山水泥有限责任有限公司',
 108: '介休市昌盛煤气化有限公司',
 109: '山西成功汽车制造有限公司',
 110: '山西交城县万城耐火材料有限公司',
 111: '山西灵石金地煤化有限责任公司',
 112: '长治县金龙洗煤有限公司',
 113: '山西长治联盛太义掌煤业有限公司',
 114: '山西中德塑钢型材有限责任公司',
 115: '广灵县荣暄新型建材有限公司',
 116: '繁峙县金鼎矿产品经销有限公司',
 117: '山西省繁峙县瑞峰铁选有限公司',
 118: '山西长治联盛首阳山煤业有限公司',
 119: '代县阳鑫矿业顺峰有限责任公司',
 120: '山西华圣铝业有限公司',
 121: '河津市泰合洗煤有限公司',
 122: '运城市禹门水泥有限公司',
 123: '山西省长治联盛长虹煤业有限公司',
 124: '山西磊鑫化工有限公司',
 125: '灵石县扬帆碳素科技有限公司',
 126: '山西好医生药业有限公司',
 127: '河津市宏盛选煤有限公司',
 128: '山西忻州神达金山煤业有限公司',
 129: '怀仁县昌盛煤业有限责任公司',
 130: '灵石县宏昌煤化有限公司',
 131: '阳高县仨宝纸业有限公司',
 132: '代县富祥铁矿',
 133: '山西华康药业股份有限公司',
 134: '襄汾县众泰冶炼实业有限公司',
 135: '山西忻州神达栖凤煤业有限公司',
 136: '繁峙县文溪磁选厂',
 137: '山西黄土坡煤业集团有限公司',
 138: '山西欧科起重机有限公司',
 139: '五台县瑞琪矿业有限公司',
 140: '阳高县普阳建材有限公司',
 141: '山西铺龙湾煤业有限公司',
 142: '山西云冈纸业有限公司',
 143: '山西旭泰矿业开发有限公司',
 144: '大同市拓金煤炭销售有限责任公司',
 145: '长治市南村煤化有限公司',
 146: '交城太行汽车零部件制造有限公司',
 147: '山西圣达水泥有限公司',
 148: '稷山县元亨建材有限责任公司',
 149: '山西管家营法兰锻造集团有限公司',
 150: '灵丘县闽旺冶金有限责任公司',
 151: '山西鸿晋塑胶科技有限公司',
 152: '山西鹏菲莉环保建材有限公司',
 153: '运城市新东方重钢结构有限公司',
 154: '洪洞县荣达煤业有限公司',
 155: '山西华南纸业股份有限公司',
 156: '介休市锦远选煤有限公司',
 157: '山西青科恒安矿业新材料有限公司',
 158: '朔州市豪杰米砂制品有限责任公司',
 159: '阳城县天一陶瓷有限公司',
 160: '绛县恒泰机械制造有限公司',
 161: '代县瀚航选矿厂',
 162: '新绛县耐之梦服饰制造有限公司',
 163: '绛县永恒机械厂',
 164: '代县丰瑞铁矿粉精加工厂',
 165: '山西诺博科技有限公司',
 166: '河津市恒正耐磨材料有限公司',
 167: '静乐县亨鑫建材有限公司',
 168: '运城市绛县开发区天宝化工有限公司',
 169: '运城市绛县开发区华青实业有限公司',
 170: '代县鑫光矿业有限公司',
 171: '河津市磊源石料有限公司',
 172: '山西久联宏远化工有限公司',
 173: '代县春升选矿厂',
 174: '代县金茂选矿厂',
 175: '孝义市盛宏达煤业有限公司',
 176: '代县祥源选矿厂',
 177: '华兆（运城）绿色建材科技有限公司',
 178: '临汾市紫鑫煤焦有限责任公司',
 179: '汾阳市远峰高钙石灰工业有限公司',
 180: '小松（中国）矿山设备有限公司朔州分公司',
 181: '运城运盛化工有限公司',
 182: '繁峙县繁盛矿业有限责任公司',
 183: '山西康腾威机械制造有限公司',
 184: '洪洞县舜凤煤业有限责任公司',
 185: '国家电投集团山西铝业有限公司',
 186: '山西华瑞达医化科技有限公司',
 187: '阳城县众利陶瓷有限公司',
 188: '运城万达广场商业管理有限公司',
 189: '万荣县华凯伟业建材有限公司',
 190: '永济市清华磨辊有限公司',
 191: '山西新鑫华通建材有限公司',
 192: '山西省繁峙县和胜拔丝制网加工厂',
 193: '平遥县昌旺洗煤有限公司',
 194: '山西义棠煤业有限责任公司',
 195: '太谷县昌鑫铸造有限公司',
 196: '山西省投资集团九洲再生能源有限公司',
 197: '阳城县鑫世纪建材厂',
 198: '阳泉市天承石油压裂支撑剂有限公司',
 199: '寿阳县宏源煤碳加工有限公司',
 200: '山西忻州神达惠安煤业有限公司',
 201: '阳城福龙陶瓷有限公司',
 202: '山西禹王煤炭气化有限公司',
 203: '代县程林铁矿',
 204: '平陆县文玲内燃空心砖厂',
 205: '山西美陶陶瓷有限公司',
 206: '山西通洲煤焦集团股份有限公司',
 207: '朔州丰泰实业有限公司',
 208: '汾阳市中恒橡胶有限公司',
 209: '吉县昌盛煤业有限公司',
 210: '山西省交城县车辆配件厂',
 211: '代县鑫昇塑料加工厂',
 212: '大同市通疆致路精煤有限公司',
 213: '河津市三联电力有限公司',
 214: '山西众立法兰有限公司',
 215: '中阳县信征选煤有限责任公司',
 216: '山西天大化工工程有限公司',
 217: '新绛县中信鑫泰能源有限公司',
 218: '河津市凯丰建材有限公司',
 219: '中科鸿基生物科技有限公司',
 220: '中国石油化工股份有限公司临汾煤层气分公司',
 221: '平定县天虹石油压裂支撑剂有限公司',
 222: '山西志信化工有限公司',
 223: '长治万达广场商业管理有限公司',
 224: '山西大恒泵业有限公司',
 225: '绛县九龙铸造厂',
 226: '阳城县意维亚陶瓷有限公司',
 227: '代县昊明选厂',
 228: '太原鑫聚盛德物资回收利用有限公司',
 229: '山西新鑫华通混凝土有限公司',
 230: '绛县众鑫源铸造有限公司',
 231: '山西永恒实业有限公司',
 232: '洪洞县海源煤化有限责任公司',
 233: '山西万泰水泥有限公司',
 234: '永济市凯通印染有限责任公司',
 235: '山西铁力建材有限公司',
 236: '山西繁荣富化工有限公司',
 237: '晋城市恒圣铸造有限公司',
 238: '代县沙沟选矿厂',
 239: '襄垣县乾元选煤有限公司',
 240: '绛县永立铸造厂',
 241: '代县远大铁矿粉精加工厂',
 242: '山西广立机械加工工业园有限公司',
 243: '阳城县华德建材厂',
 244: '永济派克新能源科技有限公司',
 245: '山西东辉新能有限公司',
 246: '河津市乾鑫石料经销有限公司',
 247: '山西金石陶瓷有限公司',
 248: '山西绿海农药科技有限公司',
 249: '际华三五三四制衣有限公司',
 250: '河津市廷选新型建材厂',
 251: '大同煤矿集团忻州同华煤业有限公司',
 252: '太原工具厂',
 253: '山西奇星农药有限公司',
 254: '山西芮晶玻璃有限公司',
 255: '阳泉瑞轩石油压裂支撑剂有限公司',
 256: '中阳县昌盛金属制品有限公司',
 257: '绛县东岩白灰厂',
 258: '代县全成矿产品开发有限公司',
 259: '交城正大冶金机械有限公司',
 260: '代县瑞锋选厂',
 261: '代县晋宝铁矿粉精加工厂',
 262: '山西日盛铝业有限公司',
 263: '山西胜源水泥有限公司',
 264: '山西贝特瑞新能源科技有限公司',
 265: '屯留县尔安高科光源有限责任公司',
 266: '洪洞县双益选煤厂',
 267: '代县聚鑫选矿厂',
 268: '绛县恒兴灰业有限公司',
 269: '绛县横水中鑫柳堡石料厂',
 270: '孝义市景惠煤焦有限公司',
 271: '太原金圆水泥有限公司',
 272: '阳城县奥美包装制品有限公司',
 273: '阳城县时代陶瓷有限公司',
 274: '介休市德峰煤化有限公司',
 275: '山西帅峰碳素有限公司',
 276: '交城县通用铸造有限公司',
 277: '闻喜县泰合活性钙有限公司',
 278: '山西鑫冶华盛机械制造有限公司',
 279: '洪洞县民生垃圾综合处理有限公司',
 280: '阳泉市金豫龙陶粒砂有限公司',
 281: '山西乡宁乾升源焦煤有限公司',
 282: '山西金岩能源科技有限公司',
 283: '代县顺民矿粉精加工厂',
 284: '代县顺文选矿厂',
 285: '代县利鑫选矿厂',
 286: '洪洞县恒启昌贸易有限公司',
 287: '太原市恒力制造有限公司',
 288: '蒲县吴锦煤业有限责任公司',
 289: '朔州冀源特种合金技术开发有限公司',
 290: '山西宇达青铜文化艺术股份有限公司',
 291: '山西捷安盛工贸有限公司',
 292: '山西亮宇炭素有限公司',
 293: '曲沃县殿石诚石料加工有限公司',
 294: '汾阳市建明橡胶有限公司',
 295: '繁峙县虎威铁选厂',
 296: '闻喜县海丰玻璃制品有限公司',
 297: '运城市通力塑料有限公司',
 298: '新绛县信沣林汽车配件有限公司',
 299: '怀仁县宏达耐火材料有限责任公司',
 300: '太原万达广场商业管理有限公司',
 301: '侯马普天通信电缆有限公司',
 302: '汾阳市鑫隆橡胶有限公司',
 303: '代县远宏选矿厂',
 304: '岢岚县西街砖厂',
 305: '平定县栋宇建材有限公司',
 306: '万荣县西村乡西村新国砖厂',
 307: '交城荣盛机械制造有限公司',
 308: '山西金国昌精煤有限公司',
 309: '绛县飞龙高钙厂',
 310: '阳城县盛世陶瓷有限公司',
 311: '太谷县北阳容晟玛钢有限公司',
 312: '山西华拓铝业有限公司',
 313: '原平宏祥选煤科技有限公司',
 314: '永济市润泽新型建材有限公司',
 315: '静乐县裕达能源清洁利用有限公司',
 316: '洪洞县赵城昭阳洗煤厂',
 317: '山西燃气产业集团有限公司原平液化分公司',
 318: '汾阳市恒泰焦化有限公司',
 319: '山西新凯盛不锈钢制品有限公司',
 320: '山西键健铝业科技有限公司',
 321: '山西富池铝业有限公司',
 322: '代县恒通矿粉精加工厂',
 323: '交城县世同铸造合金有限公司',
 324: '山西宇泽包装制品有限公司',
 325: '代县祥荣井沟选矿厂',
 326: '翼城县里砦镇神沟石料厂',
 327: '山西长治经坊庄子河煤业有限公司',
 328: '代县雍泽选矿厂',
 329: '潞城市明柳环保建材有限公司',
 330: '晋城市锐锡铸造有限公司',
 331: '山西正大制管有限公司',
 332: '代县亿鑫塑料有限公司',
 333: '河津市泰达选煤有限公司',
 334: '大同同星抗生素有限责任公司',
 335: '汾阳市鸿盛橡胶有限公司',
 336: '阳城县宇东陶瓷有限公司',
 337: '山西古特金铸造有限公司',
 338: '中阳县百胜选煤有限公司',
 339: '晋中万达广场商业管理有限公司',
 340: '闻喜县天润昌信新型材料有限公司',
 341: '山西古交煤焦集团金之中煤业有限公司',
 342: '中阳县宁远石料厂',
 343: '古县金翔龙煤业有限责任公司',
 344: '山西铭宇化工有限责任公司',
 345: '山西中北工贸有限公司',
 346: '交城县玄中锅炉辅机有限公司',
 347: '河津市玉鑫工贸有限公司',
 348: '闻喜县华圣塑料制品有限公司',
 349: '山西煤炭运销集团榆次巍山煤业有限公司',
 350: '翼城新虎威矿山环境治理有限公司',
 351: '长治市新埔木糖有限公司',
 352: '山西景元德建材有限公司',
 353: '际华三五三四运城工业物流园有限公司',
 354: '侯马当家面粉股份有限公司',
 355: '黎城县长福煤气焦化有限公司',
 356: '长治高测新材料科技有限公司',
 357: '阳城县德福建材厂',
 358: '汾阳市俊宝橡胶厂',
 359: '翼城县宏金源矿业有限责任公司',
 360: '山西石佳建材有限公司',
 361: '闻喜县河底林鸿塑料加工部',
 362: '介休市煜业选煤有限公司',
 363: '临猗县力达纸业有限公司',
 364: '平陆县虞瑞建筑材料有限公司',
 365: '山西格瑞特建筑科技股份有限公司',
 366: '代县凤凰观鑫盛铁矿有限公司',
 367: '山西海玉园食品有限公司',
 368: '代县宏昌旺矿粉加工有限公司',
 369: '山西祁县会龙玻璃器皿有限公司',
 370: '代县郭建邦选矿厂',
 371: '洪洞县诚信洗煤厂',
 372: '代县增富矿粉精加工厂',
 373: '繁峙县中虎峪选厂',
 374: '静乐县恒通洗煤有限公司',
 375: '山西东鑫衡隆机械制造股份有限公司',
 376: '洪洞县康德煤业有限公司',
 377: '山西利民工业有限责任公司',
 378: '阳泉市金亮经贸有限公司',
 379: '洪洞县赵城镇明达洗煤厂',
 380: '代县大红才矿业有限公司第三分公司',
 381: '夏县实金建材有限公司',
 382: '山西帝思曼特殊金属有限公司',
 383: '怀仁县江鑫石料厂',
 384: '闻喜县天益新材料有限公司',
 385: '平遥县金日通机械制造有限公司',
 386: '吕梁永宁煤焦集团有限责任公司',
 387: '代县盛泰选矿厂',
 388: '山西粮缘金土地科技股份有限公司',
 389: '山西泰元铜业有限公司',
 390: '河津市众鑫灰业有限公司',
 391: '汾阳市三宇橡胶有限公司',
 392: '山西澳兴果业有限公司',
 393: '交城县向东铸造厂',
 394: '山西海顺线缆有限公司',
 395: '平陆康乐橡塑科技开发有限公司',
 396: '阳城县华冠陶瓷有限公司',
 397: '原平市利达建材有限公司',
 398: '代县强盛选矿厂',
 399: '河津市华晟能源有限公司',
 400: '灵石县鑫和垃圾焚烧发电有限公司',
 401: '代县杨兴铁矿粉精加工厂',
 402: '洪洞县昕海煤化有限公司',
 403: '山西中圣恒磁材料有限公司',
 404: '山西金兰化工股份有限公司',
 405: '永济聚鑫混凝土有限公司',
 406: '山西隆源达选煤有限公司',
 407: '孝义市金精化工有限公司',
 408: '原平市昌鑫矿业有限公司',
 409: '代县盛发铁矿粉精加工厂',
 410: '山西恒运制衣有限公司',
 411: '阳城县大自然陶瓷有限责任公司',
 412: '代县黎明矿业有限公司',
 413: '寿阳县佳宁煤炭运销有限公司',
 414: '交城县兴达铸造有限公司',
 415: '山西斯普瑞机械制造股份有限公司',
 416: '岚县三鑫实业继亨铸造有限公司',
 417: '山西博阳玻璃有限公司',
 418: '山西通六仿古建材股份有限公司',
 419: '代县峪口乡西曲网沟铁矿有限公司',
 420: '太原市玉磊预拌混凝土有限公司',
 421: '山西鼎荣冷弯型钢有限公司',
 422: '翼城县钢强选厂',
 423: '山西中煤四达机电设备有限公司',
 424: '汾阳市明盛橡胶有限公司',
 425: '交城县建升煤炭加工有限公司',
 426: '代县宏泰矿业有限责任公司',
 427: '山西源盛铸锻实业有限公司',
 428: '万达商业管理集团有限公司大同分公司',
 429: '闻喜县远华冶金材料有限公司',
 430: '山西省晨辉商品混凝土配送有限公司',
 431: '汾阳市鸿涛废旧橡胶再生研发有限公司',
 432: '山西晋升昌锻件制造股份有限公司',
 433: '运城市盐湖区晋运水泥厂',
 434: '山西昊坤法兰集团有限公司',
 435: '翼城县华晋煤业有限公司',
 436: '寿阳县世纪精细化工有限公司',
 437: '太原煤炭气化（集团）有限责任公司东河煤矿',
 438: '绛县恒强工贸有限公司',
 439: '稷山县华越建材有限公司',
 440: '汾阳市琰峰橡胶有限公司',
 441: '山西古县金谷煤业有限公司',
 442: '阳城县龙达陶瓷有限公司',
 443: '山西典石晨晶科技有限公司交城县公司',
 444: '太原市建泰石料有限公司',
 445: '华兆东南（运城）绿色建筑集成有限公司',
 446: '山西启腾机械制造有限公司',
 447: '岢岚县隆鑫洗煤有限责任公司',
 448: '山西福鑫机械铸造有限公司',
 449: '交城县鑫港煤业有限公司',
 450: '汾阳市致祥胶业有限公司',
 451: '太原市双丰特种钢有限公司',
 452: '朔州市二马马混凝土有限公司',
 453: '阳城县金龙陶瓷有限公司',
 454: '朔州市程源建材有限公司',
 455: '山西煤炭进出口集团蒲县豹子沟煤业有限公司',
 456: '山西新永鑫铸造有限公司',
 457: '侯马市鑫圣建材有限公司',
 458: '山西文义活性钙有限公司',
 459: '代县泉鑫机械制造有限公司',
 460: '山西天顺油任管业有限公司',
 461: '定襄县伟业圣精密锻压有限公司',
 462: '山西天然气有限公司晋中液化分公司',
 463: '汾阳市润恒橡胶有限公司',
 464: '中阳县嘉启金属丝网厂',
 465: '万荣县南张太赵克亮砖场',
 466: '山西骏和高钙石灰制品有限公司',
 467: '朔州绿能电力设备有限公司',
 468: '河津市方达洗煤有限公司',
 469: '山西腾飞石油钻具有限公司',
 470: '交城鑫冲特种铸钢厂',
 471: '山西大禹生物工程股份有限公司',
 472: '汾阳市明兴橡胶有限公司',
 473: '代县兴源机械加工厂',
 474: '中阳县辉翼建材有限公司',
 475: '代县宏源铁矿粉精加工厂',
 476: '中联煤层气有限责任公司沁水分公司',
 477: '永济市城北区永民砖厂',
 478: '泽州县宏瑞达建材有限公司',
 479: '河津市温津贸易有限责任公司',
 480: '泽州县富宏建材厂',
 481: '阳光城物业服务有限公司太原分公司',
 482: '阳城县惠阳新能源发展有限公司',
 483: '长子县东宝能煤层气开发有限公司',
 484: '山西中兴网信科技有限公司',
 485: '阳城县方圆陶瓷琉璃研发中心',
 486: '河津市天桥石料有限公司',
 487: '长治市诚晟市政工程有限公司长治郊区沥青砼分公司',
 488: '代县俊旺精矿粉深加工厂',
 489: '万荣县舒沐集中供热中心',
 490: '山西雁门清高食业有限责任公司',
 491: '神池县尊益供热有限公司',
 492: '代县荣泰选厂',
 493: '城关镇砖厂',
 494: '浑源县热力有限公司',
 495: '河津市奥忻玻璃有限公司',
 496: '山西兴隆山循环科技发展有限公司',
 497: '代县华通矿业有限公司',
 498: '代县金升铁矿有限公司',
 499: '洪洞县茂延洗煤有限公司',
 500: '临汾市热力供应有限公司',
 501: '代县隆顺铁精粉精加工有限责任公司',
 502: '中国石油天然气股份有限公司长治煤层气勘探开发分公司',
 503: '翼城县昶元纺织有限责任公司',
 504: '中石化榆济管道有限责任公司',
 505: '山西压缩天然气集团晋东有限公司',
 506: '静乐县杜家村兴盛砖厂',
 507: '翼城县鼎焱煤业有限公司',
 508: '山西旭燚化纤有限公司',
 509: '河津市神峰工贸有限公司',
 510: '山西忻州神达南岔煤业有限公司',
 511: '中环寰慧（垣曲）节能热力有限公司',
 512: '芮城县丰蕴热力有限公司',
 513: '五台县宏鑫矿业有限公司',
 514: '灵石县顺丰煤化有限公司',
 515: '广灵县平泉建筑材料厂',
 516: '河津市海利锦煤业有限公司',
 517: '左县云中云中热力有限责任公司',
 518: '翼城县恒春源商贸有限公司',
 519: '介休市明海洗煤有限公司',
 520: '寿阳县坤泰建材有限公司',
 521: '山西漳电王坪热力有限公司',
 522: '山西长宏洗煤有限公司',
 523: '翼城县信海节能环保建材有限公司',
 524: '大同市云洲区云中热力有限公司',
 525: '泽州县巴公镇靳庄谊鑫达石灰岩矿（普通合伙）',
 526: '朔州市欧鼎冶金有限公司',
 527: '盂县长枫石料厂',
 528: '阳城县明辉商贸有限公司',
 529: '天镇县张西河乡王生树砖厂',
 530: '晋城市巨通铸造有限公司',
 531: '中国石油天然气股份有限公司临汾煤层气勘探开发分公司',
 532: '山西豪钢重工股份有限公司',
 533: '长子县福源淀粉有限公司',
 534: '长治市昂晋农业科技有限公司',
 535: '山西华德冶铸有限公司',
 536: '山西豪钢锻造股份有限公司',
 537: '山西右玉东洼北煤业有限公司',
 538: '五台县宏远矿业有限公司',
 539: '忻州市三源煤矿机械有限公司',
 540: '山西右玉教场坪煤业有限公司',
 541: '忻州市九龙制砖有限公司',
 542: '山西泽州天泰和瑞煤业有限公司',
 543: '山西进钰祥煤业有限公司',
 544: '智海企业集团榆次水泥有限公司',
 545: '山西教场坪集团玉岭煤业有限公司',
 546: '山西恩泽生物技术有限公司',
 547: '原平市章腔矿业有限公司',
 548: '山西沁和能源集团曲堤煤业有限公司',
 549: '河曲县恒得盛建材有限公司',
 550: '运城恒舜通投资控股集团有限公司',
 551: '阳城县九龙陶瓷有限公司',
 552: '原平市界河铺通达砖厂',
 553: '河曲县正大新型墙体材料有限公司',
 554: '朔州恒锐达建陶有限公司',
 555: '五台县同丰园新型墙体材料有限公司',
 556: '代县万隆铁矿粉精加工厂',
 557: '河曲县楼子营宏基砖厂',
 558: '繁寺县越红磁选厂',
 559: '山西磊发氧化钙有限公司',
 560: '山西泽州天泰西陈庄煤业有限公司',
 561: '忻州市忻府区加禾砖厂',
 562: '山西宝山矿业有限公司',
 563: '忻州市忻府区向阳制砖厂',
 564: '原平市下政化宏发选矿厂',
 565: '平遥县金众煤焦有限责任公司',
 566: '山西保利平山煤业股份有限公司',
 567: '山西兴原选矿有限公司',
 568: '定襄县四通铸锻有限责任公司',
 569: '忻州市忻府区忻口新鑫砖厂',
 570: '五台县同丰园煤炭洗选有限公司',
 571: '忻州市忻府区新宏达砖厂',
 572: '武乡县昱昇建材有限公司',
 573: '五台县豆村麻黄沟铁矿有限公司',
 574: '代县双立选厂',
 575: '忻州市铁牛水泥粉磨有限公司',
 576: '定襄县天元锻造有限公司',
 577: '山西省晋中万邦工贸有限公司',
 578: '河曲县晋华新型建筑材料有限公司',
 579: '忻州市忻府区新飞龙砖厂',
 580: '河曲县新振机械制造有限公司',
 581: '山西紫金矿业有限公司',
 582: '繁峙县兴隆矿业有限责任公司',
 583: '山西沁和能源集团南凹寺煤业有限公司',
 584: '山西宏特煤化工有限公司',
 585: '忻州市逯华墙材有限公司',
 586: '五台县德峰矿业有限公司',
 587: '沁和能源集团有限公司永安煤矿',
 588: '繁峙县义联金矿有限公司',
 589: '河曲县裕丰农业工程机械商贸中心',
 590: '交城县明鑫铸造厂',
 591: '忻州市金山矿业有限责任公司',
 592: '山西绿洲纺织有限责任公司',
 593: '忻州市通源矿业有限责任公司',
 594: '代县宏威水泥有限责任公司',
 595: '河曲县宏达机械制造有限公司'}

In [220]:
def get_userid(df):
    j=1
    i=1
    while(i!=len(df)):
        df.iloc[i,0] = get_user_id(df.iloc[i,2])
        j=j+1
        i=i+1
    return df

def get_user_id(v):
    for i,j in name_dict.items():
        if j==v:
            return i

In [221]:
get_userid(df)

,用户id,用电单元id,用户名称,用电单元名称,时间,0:00:00,0:15:00,0:30:00,0:45:00,1:00:00,...,22:00:00,22:15:00,22:30:00,22:45:00,23:00:00,23:15:00,23:30:00,23:45:00,00:00:00,0
0,0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-01,0.000,0.000,0.000,0.000,0.020,...,0.118,0.098,0.098,0.118,0.098,0.118,0.078,0.274,NaN,NaN
1,251,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-02,0.000,0.039,0.118,0.098,0.118,...,0.098,0.118,0.098,0.098,0.098,0.118,0.078,0.235,NaN,0.0
2,251,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-03,0.000,0.039,0.118,0.098,0.098,...,0.118,0.059,0.118,0.098,0.098,0.118,0.098,0.274,NaN,0.0
3,251,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-04,0.000,0.039,0.098,0.118,0.098,...,0.000,0.000,0.020,0.000,0.000,0.000,0.000,0.020,NaN,0.0
4,251,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-05,0.000,0.000,0.000,0.000,0.020,...,0.098,0.118,0.098,0.098,0.098,0.098,0.098,0.255,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59253,68,31319212,高平市全兴发展有限公司,高平市全兴发展有限公司31319212,2020-12-30,0.000,0.014,0.000,0.014,0.000,...,0.000,0.014,0.000,0.014,0.000,0.014,0.000,0.000,NaN,59253.0
59254,13,31319457,高平市安顺兴选煤有限公司,高平市安顺兴选煤有限公司31319457,2020-12-30,0.009,0.005,0.009,0.009,0.005,...,0.005,0.009,0.014,0.005,0.009,0.009,0.009,0.009,NaN,59254.0
59255,90,31347514,高平市晋昌洗煤有限公司,高平市晋昌洗煤有限公司31347514,2020-12-30,0.114,0.123,0.114,0.133,0.114,...,0.123,0.114,0.123,0.114,0.133,0.114,0.123,0.114,NaN,59255.0
59256,92,1767039849,黎城太行钢铁有限公司,黎城太行钢铁有限公司1767039849,2020-12-30,7.187,7.187,6.534,6.534,6.534,...,6.534,6.534,6.534,6.534,6.534,5.881,6.534,5.881,NaN,59256.0
59257,92,9885871,黎城太行钢铁有限公司,黎城太行钢铁有限公司9885871,2020-12-30,1.307,3.267,1.960,2.614,2.614,...,2.614,2.614,1.960,2.614,1.960,1.307,2.614,1.960,NaN,59257.0

In [161]:
df.iloc[:,-2]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
59253   NaN
59254   NaN
59255   NaN
59256   NaN
59257   NaN
Name: 00:00:00, Length: 59258, dtype: float64

In [151]:
# df = df.reset_index(drop=True)
# df
df.to_excel(r'user_unit.xlsx')

In [222]:
df1 = pd.DataFrame()
df1['用户id'] = df['用户id']
df1['用户名称'] = df['用户名称']

In [224]:
# df1 = df1.reset_index(drop=True)
df1

       用户id              用户名称
0         0  大同煤矿集团忻州同华煤业有限公司
1       251  大同煤矿集团忻州同华煤业有限公司
2       251  大同煤矿集团忻州同华煤业有限公司
3       251  大同煤矿集团忻州同华煤业有限公司
4       251  大同煤矿集团忻州同华煤业有限公司
...     ...               ...
59253    68       高平市全兴发展有限公司
59254    13      高平市安顺兴选煤有限公司
59255    90       高平市晋昌洗煤有限公司
59256    92        黎城太行钢铁有限公司
59257    92        黎城太行钢铁有限公司

[59258 rows x 2 columns]

In [223]:
df1.duplicated().sum()

58661

In [225]:
df1.drop_duplicates(inplace=True)
df1

       用户id              用户名称
0         0  大同煤矿集团忻州同华煤业有限公司
1       251  大同煤矿集团忻州同华煤业有限公司
31      212     大同市通疆致路精煤有限公司
62      334     大同同星抗生素有限责任公司
124     203            代县程林铁矿
...     ...               ...
46567   510    山西忻州神达南岔煤业有限公司
46587   521      山西漳电王坪热力有限公司
46613   517    左县云中云中热力有限责任公司
46632   494         浑源县热力有限公司
53576   534     长治市昂晋农业科技有限公司

[597 rows x 2 columns]

In [227]:
df1[df1['用户名称'].duplicated()]

   用户id              用户名称
1   251  大同煤矿集团忻州同华煤业有限公司

In [194]:
df1['用户名称'].drop_duplicates(inplace=True )
df1

        用户id              用户名称
0          0  大同煤矿集团忻州同华煤业有限公司
31         1     大同市通疆致路精煤有限公司
62         2     大同同星抗生素有限责任公司
124        3            代县程林铁矿
248        4           代县春升选矿厂
...      ...               ...
59252  33281       阳高县瑞星建材有限公司
59253  33282       高平市全兴发展有限公司
59254  33283      高平市安顺兴选煤有限公司
59255  33284       高平市晋昌洗煤有限公司
59256  33285        黎城太行钢铁有限公司

[33286 rows x 2 columns]

In [228]:
df1[df1['用户名称']=='大同煤矿集团忻州同华煤业有限公司']

   用户id              用户名称
0     0  大同煤矿集团忻州同华煤业有限公司
1   251  大同煤矿集团忻州同华煤业有限公司

In [ ]:
def dropDuplicated(df):
    name = []
    for i in range(len(df)):

In [21]:
df.columns

Index(['id', '用户名称', '用电单元名称', '时间', '0:00:00 ', '  0:15:00 ', '  0:30:00 ',
       '  0:45:00', '  1:00:00 ', '  1:15:00 ',
       ...
       '  21:45:00', '  22:00:00 ', '  22:15:00 ', '  22:30:00 ', '  22:45:00',
       '  23:00:00 ', '  23:15:00 ', '  23:30:00 ', '  23:45:00 ', '00:00:00'],
      dtype='object', length=101)

In [104]:
df2 = df.copy()

In [105]:
name_list = df.columns.values

In [106]:
df2.columns = [i.strip() for i in name_list]
df2.columns

Index(['id', '用户名称', '用电单元名称', '时间', '0:00:00', '0:15:00', '0:30:00',
       '0:45:00', '1:00:00', '1:15:00',
       ...
       '21:45:00', '22:00:00', '22:15:00', '22:30:00', '22:45:00', '23:00:00',
       '23:15:00', '23:30:00', '23:45:00', '00:00:00'],
      dtype='object', length=101)

In [43]:
 df2.iloc[:,4], df2.iloc[:,5], df.iloc[:,4]+df.iloc[:,5]

(0        0.000
 1        0.000
 2        0.000
 3        0.000
 4        0.000
          ...
 59253    0.000
 59254    0.009
 59255    0.114
 59256    7.187
 59257    1.307
 Name: 0:00:00, Length: 59258, dtype: float64,
 0        0.000
 1        0.039
 2        0.039
 3        0.039
 4        0.000
          ...
 59253    0.014
 59254    0.005
 59255    0.123
 59256    7.187
 59257    3.267
 Name: 0:15:00, Length: 59258, dtype: float64,
 0         0.000
 1         0.039
 2         0.039
 3         0.039
 4         0.000
           ...
 59253     0.014
 59254     0.014
 59255     0.237
 59256    14.374
 59257     4.574
 Length: 59258, dtype: float64)

In [83]:
def get_hour_list(hour):
    hour_= []
    for i,j in enumerate(name_list[4:]):
        if i%4==0:
            j = j.strip()
            hour_.append(j)
    return hour_

In [107]:
hour_name = get_hour_list(name_list)
hour_name[-1] = '24:00:00'
hour_name

['0:00:00',
 '1:00:00',
 '2:00:00',
 '3:00:00',
 '4:00:00',
 '5:00:00',
 '6:00:00',
 '7:00:00',
 '8:00:00',
 '9:00:00',
 '10:00:00',
 '11:00:00',
 '12:00:00',
 '13:00:00',
 '14:00:00',
 '15:00:00',
 '16:00:00',
 '17:00:00',
 '18:00:00',
 '19:00:00',
 '20:00:00',
 '21:00:00',
 '22:00:00',
 '23:00:00',
 '24:00:00']

In [108]:
col_name = [i.strip() for i in df2.columns]
col_name[-1]="24:00:00"

In [109]:
df2.columns = col_name
df2.columns

Index(['id', '用户名称', '用电单元名称', '时间', '0:00:00', '0:15:00', '0:30:00',
       '0:45:00', '1:00:00', '1:15:00',
       ...
       '21:45:00', '22:00:00', '22:15:00', '22:30:00', '22:45:00', '23:00:00',
       '23:15:00', '23:30:00', '23:45:00', '24:00:00'],
      dtype='object', length=101)

In [114]:
type(df2.iloc[1,-1])

numpy.float64

In [115]:
for i in range(len(df2["24:00:00"])):
    df2.iloc[i,-1] =0
df2["24:00:00"]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
59253    0.0
59254    0.0
59255    0.0
59256    0.0
59257    0.0
Name: 24:00:00, Length: 59258, dtype: float64

In [116]:
def merge_col(df):
    i=8
    for j in range(24):
        df.iloc[:,i] = df.iloc[:,i-1]+df.iloc[:,i-2]+df.iloc[:,i-3]+df.iloc[:,i]
        i = i+4
    return df

In [117]:
merge_col(df2)

,id,用户名称,用电单元名称,时间,0:00:00,0:15:00,0:30:00,0:45:00,1:00:00,1:15:00,...,21:45:00,22:00:00,22:15:00,22:30:00,22:45:00,23:00:00,23:15:00,23:30:00,23:45:00,24:00:00
0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-01,0.000,0.000,0.000,0.000,0.020,0.000,...,0.098,0.412,0.098,0.098,0.118,0.412,0.118,0.078,0.274,0.470
1,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-02,0.000,0.039,0.118,0.098,0.373,0.098,...,0.039,0.274,0.118,0.098,0.098,0.412,0.118,0.078,0.235,0.431
2,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-03,0.000,0.039,0.118,0.098,0.353,0.098,...,0.118,0.432,0.059,0.118,0.098,0.373,0.118,0.098,0.274,0.490
3,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-04,0.000,0.039,0.098,0.118,0.353,0.118,...,0.000,0.020,0.000,0.020,0.000,0.020,0.000,0.000,0.020,0.020
4,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-05,0.000,0.000,0.000,0.000,0.020,0.000,...,0.098,0.392,0.118,0.098,0.098,0.412,0.098,0.098,0.255,0.451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59253,31319212,高平市全兴发展有限公司,高平市全兴发展有限公司31319212,2020-12-30,0.000,0.014,0.000,0.014,0.028,0.014,...,0.014,0.014,0.014,0.000,0.014,0.028,0.014,0.000,0.000,0.014
59254,31319457,高平市安顺兴选煤有限公司,高平市安顺兴选煤有限公司31319457,2020-12-30,0.009,0.005,0.009,0.009,0.028,0.009,...,0.014,0.033,0.009,0.014,0.005,0.037,0.009,0.009,0.009,0.027
59255,31347514,高平市晋昌洗煤有限公司,高平市晋昌洗煤有限公司31347514,2020-12-30,0.114,0.123,0.114,0.133,0.484,0.123,...,0.114,0.474,0.114,0.123,0.114,0.484,0.114,0.123,0.114,0.351
59256,1767039849,黎城太行钢铁有限公司,黎城太行钢铁有限公司1767039849,2020-12-30,7.187,7.187,6.534,6.534,26.789,6.534,...,7.187,28.095,6.534,6.534,6.534,26.136,5.881,6.534,5.881,18.296
59257,9885871,黎城太行钢铁有限公司,黎城太行钢铁有限公司9885871,2020-12-30,1.307,3.267,1.960,2.614,10.455,1.960,...,1.960,9.148,2.614,1.960,2.614,9.148,1.307,2.614,1.960,5.881

In [59]:
df2.columns[5:]

Index(['0:15:00', '0:30:00', '0:45:00', '1:00:00', '1:15:00', '1:30:00',
       '1:45:00', '2:00:00', '2:15:00', '2:30:00', '2:45:00', '3:00:00',
       '3:15:00', '3:30:00', '3:45:00', '4:00:00', '4:15:00', '4:30:00',
       '4:45:00', '5:00:00', '5:15:00', '5:30:00', '5:45:00', '6:00:00',
       '6:15:00', '6:30:00', '6:45:00', '7:00:00', '7:15:00', '7:30:00',
       '7:45:00', '8:00:00', '8:15:00', '8:30:00', '8:45:00', '9:00:00',
       '9:15:00', '9:30:00', '9:45:00', '10:00:00', '10:15:00', '10:30:00',
       '10:45:00', '11:00:00', '11:15:00', '11:30:00', '11:45:00', '12:00:00',
       '12:15:00', '12:30:00', '12:45:00', '13:00:00', '13:15:00', '13:30:00',
       '13:45:00', '14:00:00', '14:15:00', '14:30:00', '14:45:00', '15:00:00',
       '15:15:00', '15:30:00', '15:45:00', '16:00:00', '16:15:00', '16:30:00',
       '16:45:00', '17:00:00', '17:15:00', '17:30:00', '17:45:00', '18:00:00',
       '18:15:00', '18:30:00', '18:45:00', '19:00:00', '19:15:00', '19:30:00',
       '19:45:00', '20:00:00', '20:15:00', '20:30:00', '20:45:00', '21:00:00',
       '21:15:00', '21:30:00', '21:45:00', '22:00:00', '22:15:00', '22:30:00',
       '22:45:00', '23:00:00', '23:15:00', '23:30:00', '23:45:00', '00:00:00'],
      dtype='object')

In [118]:
for i in df2.columns[5:]:
    if i not in hour_name:
        del df2[i]
        
df2.columns

Index(['id', '用户名称', '用电单元名称', '时间', '0:00:00', '1:00:00', '2:00:00',
       '3:00:00', '4:00:00', '5:00:00', '6:00:00', '7:00:00', '8:00:00',
       '9:00:00', '10:00:00', '11:00:00', '12:00:00', '13:00:00', '14:00:00',
       '15:00:00', '16:00:00', '17:00:00', '18:00:00', '19:00:00', '20:00:00',
       '21:00:00', '22:00:00', '23:00:00', '24:00:00'],
      dtype='object')

In [119]:
df2["0:00:00"] = df2["0:00:00"]+df2["24:00:00"]
df2

,id,用户名称,用电单元名称,时间,0:00:00,1:00:00,2:00:00,3:00:00,4:00:00,5:00:00,...,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,24:00:00
0,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-01,0.470,0.020,0.000,0.040,0.020,0.020,...,0.412,0.432,0.412,0.412,0.412,0.412,0.432,0.412,0.412,0.470
1,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-02,0.431,0.373,0.412,0.412,0.432,0.432,...,0.020,0.000,0.020,0.000,0.020,0.000,0.020,0.274,0.412,0.431
2,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-03,0.490,0.353,0.392,0.412,0.412,0.432,...,0.020,0.138,0.412,0.412,0.412,0.412,0.412,0.432,0.373,0.490
3,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-04,0.020,0.353,0.432,0.432,0.412,0.412,...,0.020,0.020,0.000,0.059,0.334,0.040,0.079,0.020,0.020,0.020
4,2165125418,大同煤矿集团忻州同华煤业有限公司,大同煤矿集团忻州同华煤业有限公司2165125418,2020-08-05,0.451,0.020,0.079,0.432,0.412,0.235,...,0.118,0.040,0.000,0.020,0.059,0.333,0.392,0.392,0.412,0.451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59253,31319212,高平市全兴发展有限公司,高平市全兴发展有限公司31319212,2020-12-30,0.014,0.028,0.028,0.028,0.014,0.028,...,0.028,0.028,0.042,0.028,0.028,0.028,0.028,0.014,0.028,0.014
59254,31319457,高平市安顺兴选煤有限公司,高平市安顺兴选煤有限公司31319457,2020-12-30,0.036,0.028,0.032,0.033,0.032,0.032,...,0.041,0.046,0.046,0.041,0.036,0.041,0.038,0.033,0.037,0.027
59255,31347514,高平市晋昌洗煤有限公司,高平市晋昌洗煤有限公司31347514,2020-12-30,0.465,0.484,0.483,0.483,0.483,0.474,...,0.027,0.036,0.046,0.094,0.417,0.465,0.474,0.474,0.484,0.351
59256,1767039849,黎城太行钢铁有限公司,黎城太行钢铁有限公司1767039849,2020-12-30,25.483,26.789,26.136,28.748,26.789,26.789,...,24.177,24.830,26.136,27.442,26.789,26.789,29.402,28.095,26.136,18.296
59257,9885871,黎城太行钢铁有限公司,黎城太行钢铁有限公司9885871,2020-12-30,7.188,10.455,8.495,9.802,11.762,9.802,...,9.802,11.109,9.148,11.108,9.148,9.149,10.456,9.148,9.148,5.881

In [121]:
df2["时间"].apply(str)
df2["时间"]

0       2020-08-01
1       2020-08-02
2       2020-08-03
3       2020-08-04
4       2020-08-05
           ...
59253   2020-12-30
59254   2020-12-30
59255   2020-12-30
59256   2020-12-30
59257   2020-12-30
Name: 时间, Length: 59258, dtype: datetime64[ns]

In [ ]:
df2.to_excel